import React from 'react';
import Layout from '../components/Layout.jsx';
import SectionTitle from '../components/SectionTitle.jsx';
import DeviceShot from '../components/DeviceShot.jsx';
import Cta from '../components/Cta.jsx';
import { BrainCircuit, FileSearch, Scale, Workflow, FileText, Sparkles, CheckCircle2, AlertTriangle } from 'lucide-react';

export default function AiPage(){
  return <Layout>
    <section className="page-hero page-hero-ai"><div className="container split-showcase"><div><span className="hero-kicker dark"><span/>DERKENAR AI</span><h1>Dosyanızla çalışan yapay zekâ.</h1><p>Derkenar AI, hukuki çalışma sürecini hızlandırmak için dosya bağlamı, analiz edilmiş belgeler ve yapılandırılmış kullanıcı girdileriyle çalışan ayrı akışlar sunar.</p><div className="notice"><AlertTriangle/>Yapay zekâ çıktıları çalışma ve ön değerlendirme amaçlıdır; hukuki işlemden önce avukat tarafından kontrol edilmelidir.</div></div><DeviceShot src="/screenshots/dosyaya-sor.jpg" alt="Derkenar AI Dosyaya Sor"/></div></section>
    <section className="section section-white"><div className="container"><SectionTitle eyebrow="DOSYA ODAKLI AKIŞLAR" title="AI yalnızca metin üretmez; dosyanın çalışma akışına bağlanır." text="Dosya hafızası, görevler, duruşmalar, toplantılar, notlar ve analiz edilmiş belgeler üzerinde dosya odaklı çalışma deneyimi." align="center"/><div className="feature-grid three"><article className="detail-feature"><span><BrainCircuit/></span><h2>Dosyaya Sor</h2><p>Dosya kayıtları üzerinden kritik riskler, yaklaşan işlemler, eksik bilgi veya deliller gibi konularda soru-cevap akışı.</p></article><article className="detail-feature"><span><Scale/></span><h2>Duruşmaya Hazırla</h2><p>Dosya bağlamını kullanarak duruşma öncesi çalışma ve hazırlık sürecine destek veren ayrı AI akışı.</p></article><article className="detail-feature"><span><FileSearch/></span><h2>Dosyayı Tamamla</h2><p>Dosyanın mevcut kayıtlarını ve içeriğini değerlendirerek eksik veya tamamlanması gereken noktaları çalışma akışına taşımaya yardımcı olur.</p></article><article className="detail-feature"><span><Workflow/></span><h2>Otomatik görev oluşturma</h2><p>AI çıktılarındaki iş adımlarını görev modülüne taşıyarak öneriyi ofis operasyonuna dönüştürür.</p></article><article className="detail-feature"><span><Sparkles/></span><h2>Belge analizi</h2><p>Desteklenen hukuki belgeler üzerinde yapılandırılmış inceleme ve analiz çalıştırın.</p></article><article className="detail-feature"><span><FileText/></span><h2>Hukuki şablon oluşturma</h2><p>Mahkeme, dava konusu, olaylar, talepler ve deliller gibi girdilerden avukat incelemesine hazır ilk taslak oluşturun.</p></article></div></div></section>
    <section className="section ai-showcase"><div className="container split-showcase"><div><SectionTitle eyebrow="YAPAY ZEKÂ ÇALIŞMA ALANI" title="Belge analizi, hukuki ön değerlendirme ve şablon üretimi ayrı akışlarda." text="Kullanıcı hangi çalışma türünü yaptığını bilir; AI çıktıları hukuki karar yerine hazırlık ve inceleme aracı olarak konumlanır." light/><ul className="check-list-pro light"><li><CheckCircle2/>Belge Analizi</li><li><CheckCircle2/>Hukuki Ön Değerlendirme</li><li><CheckCircle2/>Hukuki Şablon Oluştur</li><li><CheckCircle2/>Avukat kontrolü uyarıları</li></ul></div><DeviceShot src="/screenshots/ai2.jpg" alt="Derkenar Yapay Zekâ Çalışma Alanı"/></div></section>
    <Cta/>
  </Layout>
}
